add_newline = false
format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$status\
$character"""

[character]
success_symbol = '[\$](fg:bright-green)'
error_symbol = '[\$](fg:bright-red)'
vicmd_symbol = '[](blue)'

[directory]
truncation_length = 0
truncation_symbol = ' '
truncate_to_repo = true
style = 'yellow'

[cmd_duration]
min_time = 0
format = '[ $duration](fg:bright-yellow)'
show_milliseconds = true

[elixir]
format = '[$symbol$version \(OTP $otp_version\)]($style) '
style = 'purple'
symbol = ' '

[gcloud]
disabled = true

[git_branch]
format = '[$symbol$branch]($style) '
style = 'cyan'

[git_commit]
disabled = false
commit_hash_length = 6
tag_symbol = " "
only_detached = false
tag_disabled = false
format = '[$tag]($style) '
style = 'purple'

[git_status]
format = '( $staged$modified$renamed$deleted$untracked)($style)'
untracked = '([$count untracked ](italic fg:bright-green))'
modified = '([$count modified ](italic fg:bright-green))'
staged = '([$count modified ](italic green))'
deleted = '([$count deleted ](italic green))'
renamed = '([$count renamed ](italic green))'

[nodejs]
format = '[$symbol$version]($style) '

[package]
disabled = false

[status]
format = '[$status]($style) '
disabled = false
