" Legacy Vimscript files
" ----------------------------------------------------------------------------------------------------
source $HOME/.vim/config/global-settings.vim
source $HOME/.vim/config/plugin-settings.vim
source $HOME/.vim/config/commands.vim
source $HOME/.vim/config/mappings.vim
source $HOME/.vim/config/events.vim
